### ISSUE TITLE
Ikke mulig å slette aktiv delegering av MaskinportenSchema som er satt til ikke delegerbar og ikke synlig

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-authorization-tmp#89]
# Beskrivelse av buggen

Ref.: slack tråd i public slack for BRG som har funnet buggen:
https://altinn.slack.com/archives/C02ESDSGPN1/p1730455432959469?thread_ts=1730381088.763059&cid=C02ESDSGPN1

Det bør samtidig sjekkes at dette ikke er en feil som er arvet med inn i sletting av andre App/Ressurs delegeringer.

## Steg for å reprodusere buggen

1. Opprett MaskinportenSchema ressurs og policy, med ressursen satt som Synlig og Delegerbar
2. Logg på som API Admin for en org og deleger MaskinportenSchema fra pkt. 1 til en annen org
3. Sett MaskinportenSchema ressurs som Ikke Synlig og Ikke Delegerbar
4. Vent på Cache utløp av ResourceList API
5. Logg på som API Admin som delegerte eller mottok delegering i pkt 2.
6. Forsøk å slett mottatt eller delegert MaskinportenSchema

**Resultat:**
Feilmelding i GUI: `Kunne ikke slette`

Eksempel fra TT02:
![Image](https://github.com/user-attachments/assets/8044be1e-6328-4328-9a4f-370567869654)

**Forventet:**
Det skal være mulig å slette aktive delegeringer selv om ressursen ikke lenger er satt til Synlig for delegering eller Delegerbar.

**Comment by jonkjetiloye** [comment]
I backend er det lagt inn dobbelt sjekk på om ressursen er Delegable, hvor den ene ikke samtidig sjekker at det brukeren forsøker faktisk er delegering og ikke sletting.

Duplikat sjekk som kan fjernes:
https://github.com/Altinn/altinn-access-management/blob/main/src/Altinn.AccessManagement.Core/Services/MaskinportenSchemaService.cs#L292

MaskinportenSchemaService.ValidateMaskinportenDelegationModel:292
```
if (!resource.Delegable)
{
    result.Errors.Add("right[0].Resource", $"The resource: {resource}, is not available for delegation");
    return (result, null, null, null);
}
```

**Comment by sneha-sirure** [comment]
@jonkjetiloye Har verifisert denne buggen ok i AT22 og venter for å verifisere det i tt02.

**Comment by sneha-sirure** [comment]
@jonkjetiloye Har verifisert ok i tt02 da tror jeg vi kan lukke?
